{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: tensorflow in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (2.10.0)\n",
      "Requirement already satisfied: six>=1.12.0 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (1.15.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (3.7.4.3)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (1.6.3)\n",
      "Requirement already satisfied: protobuf<3.20,>=3.9.2 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (3.19.6)\n",
      "Requirement already satisfied: setuptools in d:\\anaconda3\\lib\\site-packages (from tensorflow) (50.3.1.post20201107)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (1.49.1)\n",
      "Requirement already satisfied: tensorflow-estimator<2.11,>=2.10.0 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (2.10.0)\n",
      "Requirement already satisfied: packaging in d:\\anaconda3\\lib\\site-packages (from tensorflow) (20.4)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (1.11.2)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (0.4.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (2.0.1)\n",
      "Requirement already satisfied: numpy>=1.20 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (1.23.3)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (14.0.6)\n",
      "Requirement already satisfied: tensorboard<2.11,>=2.10 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (2.10.1)\n",
      "Requirement already satisfied: keras<2.11,>=2.10.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (2.10.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (0.2.0)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (3.3.0)\n",
      "Requirement already satisfied: flatbuffers>=2.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (22.9.24)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (0.27.0)\n",
      "Requirement already satisfied: keras-preprocessing>=1.1.1 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (1.1.2)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorflow) (1.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in d:\\anaconda3\\lib\\site-packages (from tensorflow) (2.10.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in d:\\anaconda3\\lib\\site-packages (from astunparse>=1.6.0->tensorflow) (0.35.1)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in d:\\anaconda3\\lib\\site-packages (from packaging->tensorflow) (2.4.7)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in d:\\anaconda3\\lib\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (1.0.1)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in d:\\anaconda3\\lib\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.12.0)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in d:\\anaconda3\\lib\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (2.24.0)\n",
      "Requirement already satisfied: markdown>=2.6.8 in d:\\anaconda3\\lib\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (3.4.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in d:\\anaconda3\\lib\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.6.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in d:\\anaconda3\\lib\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (1.8.1)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from tensorboard<2.11,>=2.10->tensorflow) (0.4.6)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4; python_version >= \"3.6\" in d:\\anaconda3\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (4.9)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in d:\\anaconda3\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (5.2.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in d:\\anaconda3\\lib\\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.2.8)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in d:\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (3.0.4)\n",
      "Requirement already satisfied: idna<3,>=2.5 in d:\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2.10)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (1.25.11)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in d:\\anaconda3\\lib\\site-packages (from requests<3,>=2.21.0->tensorboard<2.11,>=2.10->tensorflow) (2020.6.20)\n",
      "Requirement already satisfied: importlib-metadata>=4.4; python_version < \"3.10\" in d:\\anaconda3\\lib\\site-packages (from markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (4.12.0)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (1.3.1)\n",
      "Requirement already satisfied: pyasn1>=0.1.3 in d:\\anaconda3\\lib\\site-packages (from rsa<5,>=3.1.4; python_version >= \"3.6\"->google-auth<3,>=1.6.3->tensorboard<2.11,>=2.10->tensorflow) (0.4.8)\n",
      "Requirement already satisfied: zipp>=0.5 in d:\\anaconda3\\lib\\site-packages (from importlib-metadata>=4.4; python_version < \"3.10\"->markdown>=2.6.8->tensorboard<2.11,>=2.10->tensorflow) (3.4.0)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in c:\\users\\user\\appdata\\roaming\\python\\python38\\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.11,>=2.10->tensorflow) (3.2.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install tensorflow --user"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: scikeras in d:\\anaconda3\\lib\\site-packages (0.9.0)\n",
      "Requirement already satisfied: packaging>=0.21 in d:\\anaconda3\\lib\\site-packages (from scikeras) (20.4)\n",
      "Requirement already satisfied: scikit-learn>=1.0.0 in d:\\anaconda3\\lib\\site-packages (from scikeras) (1.1.2)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in d:\\anaconda3\\lib\\site-packages (from packaging>=0.21->scikeras) (2.4.7)\n",
      "Requirement already satisfied: six in d:\\anaconda3\\lib\\site-packages (from packaging>=0.21->scikeras) (1.15.0)\n",
      "Requirement already satisfied: numpy>=1.17.3 in d:\\anaconda3\\lib\\site-packages (from scikit-learn>=1.0.0->scikeras) (1.23.3)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in d:\\anaconda3\\lib\\site-packages (from scikit-learn>=1.0.0->scikeras) (2.1.0)\n",
      "Requirement already satisfied: scipy>=1.3.2 in d:\\anaconda3\\lib\\site-packages (from scikit-learn>=1.0.0->scikeras) (1.5.2)\n",
      "Requirement already satisfied: joblib>=1.0.0 in d:\\anaconda3\\lib\\site-packages (from scikit-learn>=1.0.0->scikeras) (1.2.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install scikeras"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: wheel in d:\\anaconda3\\lib\\site-packages (0.35.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting pipwin\n",
      "  Downloading pipwin-0.5.2.tar.gz (7.9 kB)\n",
      "Requirement already satisfied: docopt in d:\\anaconda3\\lib\\site-packages (from pipwin) (0.6.2)\n",
      "Requirement already satisfied: requests in d:\\anaconda3\\lib\\site-packages (from pipwin) (2.24.0)\n",
      "Collecting pyprind\n",
      "  Downloading PyPrind-2.11.3-py2.py3-none-any.whl (8.4 kB)\n",
      "Requirement already satisfied: six in d:\\anaconda3\\lib\\site-packages (from pipwin) (1.15.0)\n",
      "Requirement already satisfied: beautifulsoup4>=4.9.0 in d:\\anaconda3\\lib\\site-packages (from pipwin) (4.9.3)\n",
      "Collecting js2py\n",
      "  Downloading Js2Py-0.71-py3-none-any.whl (1.0 MB)\n",
      "Requirement already satisfied: packaging in d:\\anaconda3\\lib\\site-packages (from pipwin) (20.4)\n",
      "Collecting pySmartDL>=1.3.1\n",
      "  Downloading pySmartDL-1.3.4-py3-none-any.whl (20 kB)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in d:\\anaconda3\\lib\\site-packages (from requests->pipwin) (2020.6.20)\n",
      "Requirement already satisfied: chardet<4,>=3.0.2 in d:\\anaconda3\\lib\\site-packages (from requests->pipwin) (3.0.4)\n",
      "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in d:\\anaconda3\\lib\\site-packages (from requests->pipwin) (1.25.11)\n",
      "Requirement already satisfied: idna<3,>=2.5 in d:\\anaconda3\\lib\\site-packages (from requests->pipwin) (2.10)\n",
      "Requirement already satisfied: soupsieve>1.2; python_version >= \"3.0\" in d:\\anaconda3\\lib\\site-packages (from beautifulsoup4>=4.9.0->pipwin) (2.0.1)\n",
      "Collecting pyjsparser>=2.5.1\n",
      "  Downloading pyjsparser-2.7.1.tar.gz (24 kB)\n",
      "Collecting tzlocal>=1.2\n",
      "  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)\n",
      "Requirement already satisfied: pyparsing>=2.0.2 in d:\\anaconda3\\lib\\site-packages (from packaging->pipwin) (2.4.7)\n",
      "Collecting tzdata; platform_system == \"Windows\"\n",
      "  Downloading tzdata-2022.4-py2.py3-none-any.whl (336 kB)\n",
      "Collecting pytz-deprecation-shim\n",
      "  Downloading pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)\n",
      "Collecting backports.zoneinfo; python_version < \"3.9\"\n",
      "  Downloading backports.zoneinfo-0.2.1-cp38-cp38-win_amd64.whl (38 kB)\n",
      "Building wheels for collected packages: pipwin, pyjsparser\n",
      "  Building wheel for pipwin (setup.py): started\n",
      "  Building wheel for pipwin (setup.py): finished with status 'done'\n",
      "  Created wheel for pipwin: filename=pipwin-0.5.2-py2.py3-none-any.whl size=8782 sha256=86911ca5f605b01a9fd2fef37053292183d522248c114b932b5d24c6bcc11faf\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\f4\\a8\\76\\372879a40d2d4dd7de23efd867ed37112687429b8d0dda4545\n",
      "  Building wheel for pyjsparser (setup.py): started\n",
      "  Building wheel for pyjsparser (setup.py): finished with status 'done'\n",
      "  Created wheel for pyjsparser: filename=pyjsparser-2.7.1-py3-none-any.whl size=26004 sha256=e1edc9300bdee7538e064892965cf7cbbffc80ce4ca27c62163ee47eb7b0fff3\n",
      "  Stored in directory: c:\\users\\user\\appdata\\local\\pip\\cache\\wheels\\d5\\88\\34\\ccb5bb40eb3178a134eb293e6c363928c5bcfba0b91031db76\n",
      "Successfully built pipwin pyjsparser\n",
      "Installing collected packages: pyprind, pyjsparser, tzdata, backports.zoneinfo, pytz-deprecation-shim, tzlocal, js2py, pySmartDL, pipwin\n",
      "Successfully installed backports.zoneinfo-0.2.1 js2py-0.71 pipwin-0.5.2 pySmartDL-1.3.4 pyjsparser-2.7.1 pyprind-2.11.3 pytz-deprecation-shim-0.1.0.post0 tzdata-2022.4 tzlocal-4.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "UsageError: Line magic function `%pipwin` not found.\n"
     ]
    }
   ],
   "source": [
    "%pip install wheel\n",
    "%pip install pipwin\n",
    "%pip install numpy\n",
    "%pip install pandas\n",
    "%pip install shapely"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting gdal\n",
      "  Using cached GDAL-3.5.2.tar.gz (756 kB)\n",
      "Building wheels for collected packages: gdal\n",
      "  Building wheel for gdal (setup.py): started\n",
      "  Building wheel for gdal (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for gdal\n",
      "Failed to build gdal\n",
      "Installing collected packages: gdal\n",
      "    Running setup.py install for gdal: started\n",
      "    Running setup.py install for gdal: finished with status 'error'\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'D:\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-k_1ushbv\\\\gdal\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-k_1ushbv\\\\gdal\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-wheel-wcvdqi6n'\n",
      "       cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-k_1ushbv\\gdal\\\n",
      "  Complete output (139 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_py\n",
      "  creating build\n",
      "  creating build\\lib.win-amd64-3.8\n",
      "  creating build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\gdal.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\gdalconst.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\gdalnumeric.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\gdal_array.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\gnm.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\ogr.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\osr.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\utils.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  copying osgeo\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "  creating build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal2tiles.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal2xyz.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdalattachpct.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdalcompare.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdalmove.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_calc.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_edit.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_fillnodata.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_merge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_pansharpen.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_polygonize.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_proximity.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_retile.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\gdal_sieve.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\ogrmerge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\pct2rgb.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\rgb2pct.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  copying gdal-utils\\osgeo_utils\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "  creating build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\array_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\base.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\batch_creator.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\color_palette.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\color_table.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\extent_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\gdal_argparse.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\numpy_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\osr_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\progress.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\raster_creation.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\rectangle.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  copying gdal-utils\\osgeo_utils\\auxiliary\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "  creating build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\assemblepoly.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\build_jp2_from_xml.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\classify.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\crs2crs2grid.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\densify.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\dump_jp2.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\epsg_tr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\esri2wkt.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\fft.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\fix_gpkg.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gcps2ogr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gcps2vec.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gcps2wld.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal2grd.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdalchksum.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdalcopyproj.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdalfilter.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdalident.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdalimport.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdalinfo.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdallocationinfo.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_auth.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_cp.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_create_pdf.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_ls.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_lut.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_mkdir.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_remove_towgs84.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_rm.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_rmdir.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_vrtmerge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\gdal_zip.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\get_soundg.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\histrep.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\hsv_merge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\jpeg_in_tiff_extract.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\load2odbc.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\loslas2ntv2.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\magphase.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\make_fuzzer_friendly_archive.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\mkgraticule.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogr2ogr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogr2vrt.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogrinfo.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogrupdate.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogr_build_junction_table.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogr_dispatch.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\ogr_layer_algebra.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\rel.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\tigerpoly.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\tile_extent_from_raster.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\tolatlong.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\validate_cloud_optimized_geotiff.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\validate_gpkg.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\validate_jp2.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\val_repl.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\vec_tr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\vec_tr_spat.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\wcs_virtds_params.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  copying gdal-utils\\osgeo_utils\\samples\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "  running build_ext\n",
      "  building 'osgeo._gdal' extension\n",
      "  building 'osgeo._gdalconst' extension\n",
      "  building 'osgeo._osr' extension\n",
      "  building 'osgeo._ogr' extension\n",
      "  building 'osgeo._gnm' extension\n",
      "  building 'osgeo._gdal_array' extension\n",
      "  creating build\\temp.win-amd64-3.8\n",
      "  creating build\\temp.win-amd64-3.8\\Release\n",
      "  creating build\\temp.win-amd64-3.8\\Release\\extensions\n",
      "  D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /Tcextensions/gdalconst_wrap.c /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gdalconst_wrap.obj\n",
      "  gdalconst_wrap.c\n",
      "  D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/gdal_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gdal_wrap.obj\n",
      "  gdal_wrap.cpp\n",
      "  D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/osr_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/osr_wrap.obj\n",
      "  osr_wrap.cpp\n",
      "  extensions/gdalconst_wrap.c(2703): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "  D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/gnm_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gnm_wrap.obj\n",
      "  D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/gdal_array_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gdal_array_wrap.obj\n",
      "  gnm_wrap.cpp\n",
      "  gdal_array_wrap.cpp\n",
      "  extensions/gdal_wrap.cpp(2883): fatal error C1083: Cannot open include file: 'cpl_port.h': No such file or directory\n",
      "  extensions/osr_wrap.cpp(2879): fatal error C1083: Cannot open include file: 'cpl_string.h': No such file or directory\n",
      "  extensions/gdal_array_wrap.cpp(2829): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "  extensions/gnm_wrap.cpp(2820): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "  D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/ogr_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/ogr_wrap.obj\n",
      "  ogr_wrap.cpp\n",
      "  extensions/ogr_wrap.cpp(2838): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "  error: command 'D:\\\\Visual Studio\\\\VC\\\\Tools\\\\MSVC\\\\14.26.28801\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit status 2\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for gdal\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'D:\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-k_1ushbv\\\\gdal\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-k_1ushbv\\\\gdal\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-record-6r1vrk82\\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\\anaconda3\\Include\\gdal'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-k_1ushbv\\gdal\\\n",
      "    Complete output (139 lines):\n",
      "    running install\n",
      "    running build\n",
      "    running build_py\n",
      "    creating build\n",
      "    creating build\\lib.win-amd64-3.8\n",
      "    creating build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\gdal.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\gdalconst.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\gdalnumeric.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\gdal_array.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\gnm.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\ogr.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\osr.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\utils.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    copying osgeo\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo\n",
      "    creating build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal2tiles.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal2xyz.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdalattachpct.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdalcompare.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdalmove.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_calc.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_edit.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_fillnodata.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_merge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_pansharpen.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_polygonize.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_proximity.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_retile.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\gdal_sieve.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\ogrmerge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\pct2rgb.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\rgb2pct.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    copying gdal-utils\\osgeo_utils\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo_utils\n",
      "    creating build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\array_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\base.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\batch_creator.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\color_palette.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\color_table.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\extent_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\gdal_argparse.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\numpy_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\osr_util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\progress.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\raster_creation.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\rectangle.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\util.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    copying gdal-utils\\osgeo_utils\\auxiliary\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\auxiliary\n",
      "    creating build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\assemblepoly.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\build_jp2_from_xml.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\classify.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\crs2crs2grid.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\densify.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\dump_jp2.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\epsg_tr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\esri2wkt.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\fft.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\fix_gpkg.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gcps2ogr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gcps2vec.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gcps2wld.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal2grd.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdalchksum.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdalcopyproj.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdalfilter.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdalident.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdalimport.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdalinfo.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdallocationinfo.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_auth.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_cp.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_create_pdf.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_ls.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_lut.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_mkdir.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_remove_towgs84.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_rm.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_rmdir.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_vrtmerge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\gdal_zip.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\get_soundg.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\histrep.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\hsv_merge.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\jpeg_in_tiff_extract.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\load2odbc.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\loslas2ntv2.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\magphase.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\make_fuzzer_friendly_archive.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\mkgraticule.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogr2ogr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogr2vrt.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogrinfo.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogrupdate.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogr_build_junction_table.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogr_dispatch.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\ogr_layer_algebra.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\rel.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\tigerpoly.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\tile_extent_from_raster.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\tolatlong.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\validate_cloud_optimized_geotiff.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\validate_gpkg.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\validate_jp2.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\val_repl.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\vec_tr.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\vec_tr_spat.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\wcs_virtds_params.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    copying gdal-utils\\osgeo_utils\\samples\\__init__.py -> build\\lib.win-amd64-3.8\\osgeo_utils\\samples\n",
      "    running build_ext\n",
      "    building 'osgeo._gdal' extension\n",
      "    building 'osgeo._gdalconst' extension\n",
      "    building 'osgeo._osr' extension\n",
      "    building 'osgeo._ogr' extension\n",
      "    building 'osgeo._gnm' extension\n",
      "    building 'osgeo._gdal_array' extension\n",
      "    creating build\\temp.win-amd64-3.8\n",
      "    creating build\\temp.win-amd64-3.8\\Release\n",
      "    creating build\\temp.win-amd64-3.8\\Release\\extensions\n",
      "    D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/gnm_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gnm_wrap.obj\n",
      "    D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /Tcextensions/gdalconst_wrap.c /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gdalconst_wrap.obj\n",
      "    D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/gdal_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gdal_wrap.obj\n",
      "    D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/gdal_array_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/gdal_array_wrap.obj\n",
      "    D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/ogr_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/ogr_wrap.obj\n",
      "    D:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -ID:\\anaconda3\\include -ID:\\anaconda3\\include -ID:\\anaconda3\\lib\\site-packages\\numpy\\core\\include \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include\" \"-ID:\\Visual Studio\\VC\\Tools\\MSVC\\14.26.28801\\include\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\shared\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\um\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\winrt\" \"-ID:\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt\" /EHsc /Tpextensions/osr_wrap.cpp /Fobuild\\temp.win-amd64-3.8\\Release\\extensions/osr_wrap.obj\n",
      "    gdal_array_wrap.cpp\n",
      "    gnm_wrap.cpp\n",
      "    gdalconst_wrap.c\n",
      "    gdal_wrap.cpp\n",
      "    osr_wrap.cpp\n",
      "    ogr_wrap.cpp\n",
      "    extensions/gdalconst_wrap.c(2703): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "    extensions/gdal_array_wrap.cpp(2829): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "    extensions/osr_wrap.cpp(2879): fatal error C1083: Cannot open include file: 'cpl_string.h': No such file or directory\n",
      "    extensions/gdal_wrap.cpp(2883): fatal error C1083: Cannot open include file: 'cpl_port.h': No such file or directory\n",
      "    extensions/gnm_wrap.cpp(2820): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "    extensions/ogr_wrap.cpp(2838): fatal error C1083: Cannot open include file: 'gdal.h': No such file or directory\n",
      "    error: command 'D:\\\\Visual Studio\\\\VC\\\\Tools\\\\MSVC\\\\14.26.28801\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit status 2\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'D:\\anaconda3\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-k_1ushbv\\\\gdal\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-k_1ushbv\\\\gdal\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-record-6r1vrk82\\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\\anaconda3\\Include\\gdal' Check the logs for full command output.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting fiona\n",
      "  Using cached Fiona-1.8.21.tar.gz (1.0 MB)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'D:\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gt87k77y\\\\fiona\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-gt87k77y\\\\fiona\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-udsm7_xp'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-gt87k77y\\fiona\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting geopandas\n",
      "  Using cached geopandas-0.11.1-py3-none-any.whl (1.0 MB)\n",
      "Requirement already satisfied: pyproj>=2.6.1.post1 in d:\\anaconda3\\lib\\site-packages (from geopandas) (3.4.0)\n",
      "Requirement already satisfied: packaging in d:\\anaconda3\\lib\\site-packages (from geopandas) (20.4)\n",
      "Collecting fiona>=1.8\n",
      "  Using cached Fiona-1.8.21.tar.gz (1.0 MB)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'D:\\anaconda3\\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-tt52cjxq\\\\fiona\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\User\\\\AppData\\\\Local\\\\Temp\\\\pip-install-tt52cjxq\\\\fiona\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base 'C:\\Users\\User\\AppData\\Local\\Temp\\pip-pip-egg-info-t1s_yaj8'\n",
      "         cwd: C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-tt52cjxq\\fiona\\\n",
      "    Complete output (1 lines):\n",
      "    A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "%pip install fiona\n",
    "%pip install geopandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'geopandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-1-2b51d0a0b36d>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      7\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0msklearn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpreprocessing\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mStandardScaler\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      8\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0msklearn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpipeline\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mPipeline\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 9\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mgeopandas\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mgpd\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     10\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0msklearn\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcompose\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mColumnTransformer\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'geopandas'"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense\n",
    "from scikeras.wrappers import KerasRegressor\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "import geopandas as gpd\n",
    "from sklearn.compose import ColumnTransformer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>index</th>\n",
       "      <th>address</th>\n",
       "      <th>cost_text</th>\n",
       "      <th>Bed</th>\n",
       "      <th>Bath</th>\n",
       "      <th>Park</th>\n",
       "      <th>property_type</th>\n",
       "      <th>desc_head</th>\n",
       "      <th>LocID</th>\n",
       "      <th>longitude</th>\n",
       "      <th>latitude</th>\n",
       "      <th>Median_tot_prsnl_inc_weekly</th>\n",
       "      <th>Median_rent_weekly</th>\n",
       "      <th>Median_tot_fam_inc_weekly</th>\n",
       "      <th>Median_tot_hhd_inc_weekly</th>\n",
       "      <th>total_population</th>\n",
       "      <th>SA2_NAME21</th>\n",
       "      <th>duration_mins</th>\n",
       "      <th>Offence Count</th>\n",
       "      <th>SA2_CODE_2021</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://www.domain.com.au/warrandyte-vic-3113-...</td>\n",
       "      <td>Warrandyte VIC 3113</td>\n",
       "      <td>875.0</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>3</td>\n",
       "      <td>House</td>\n",
       "      <td>mud brick magic</td>\n",
       "      <td>211021262</td>\n",
       "      <td>145.209992</td>\n",
       "      <td>-37.747366</td>\n",
       "      <td>930.0</td>\n",
       "      <td>481.0</td>\n",
       "      <td>3051.0</td>\n",
       "      <td>2779.0</td>\n",
       "      <td>8781.0</td>\n",
       "      <td>Warrandyte - Wonga Park</td>\n",
       "      <td>&gt;50.0</td>\n",
       "      <td>859.0</td>\n",
       "      <td>211021262.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                               index              address  \\\n",
       "0  https://www.domain.com.au/warrandyte-vic-3113-...  Warrandyte VIC 3113   \n",
       "\n",
       "   cost_text  Bed  Bath  Park property_type        desc_head      LocID  \\\n",
       "0      875.0    5     3     3         House  mud brick magic  211021262   \n",
       "\n",
       "    longitude   latitude  Median_tot_prsnl_inc_weekly  Median_rent_weekly  \\\n",
       "0  145.209992 -37.747366                        930.0               481.0   \n",
       "\n",
       "   Median_tot_fam_inc_weekly  Median_tot_hhd_inc_weekly  total_population  \\\n",
       "0                     3051.0                     2779.0            8781.0   \n",
       "\n",
       "                SA2_NAME21 duration_mins  Offence Count  SA2_CODE_2021  \n",
       "0  Warrandyte - Wonga Park         >50.0          859.0    211021262.0  "
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# load dataset\n",
    "property_df = pd.read_csv(\"../data/curated/full_data.csv\")\n",
    "X = property_df\n",
    "X2 = X[['SA2_NAME21']].groupby(by=\"SA2_NAME21\")[\"SA2_NAME21\"].count()\n",
    "X2 = pd.DataFrame(X2)\n",
    "X2.columns=[\"count\"]\n",
    "single_counts = X2[X2['count']==1].reset_index()['SA2_NAME21'].tolist() # can improve this later with bootstrapping\n",
    "X = X[~X[\"SA2_NAME21\"].isin(single_counts)]\n",
    "X.head(1)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'geopandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-3-b9a6154c0ebc>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mgeopandas\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mgpd\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[1;31m# sf stands for shape file\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0maustralia_sf\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mgpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mread_file\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"../data/raw/shapefiles/Statistical_area_level2/SA2_2021_AUST_GDA2020.shp\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[0maustralia_sf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mhead\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m3\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[1;31m# seperate suburbs that are in Victoria\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'geopandas'"
     ]
    }
   ],
   "source": [
    "\n",
    "# sf stands for shape file\n",
    "australia_sf = gpd.read_file(\"../data/raw/shapefiles/Statistical_area_level2/SA2_2021_AUST_GDA2020.shp\")\n",
    "australia_sf.head(3)\n",
    "# seperate suburbs that are in Victoria\n",
    "vic_sf = australia_sf[australia_sf['STE_NAME21'] == 'Victoria']\n",
    "\n",
    "# drop the null location ID values\n",
    "vic_sf.dropna(inplace=True)\n",
    "vic_sf.head(1)\n",
    "vic_sf.where(vic_sf[\"SA2_NAME21\"] == \"Seaford (Vic.)\").dropna()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "vic_centroid_sf = vic_sf\n",
    "vic_centroid_sf['geometry'] = vic_sf['geometry'].to_crs('+proj=cea').centroid.to_crs(vic_sf['geometry'].crs)\n",
    "cbd_loc = vic_centroid_sf.where(vic_centroid_sf['SA2_NAME21'] == 'Melbourne CBD - North').dropna()['geometry']\n",
    "cbd_loc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# function taken from https://stackoverflow.com/a/56661833\n",
    "\n",
    "from math import radians, cos, sin, asin, sqrt, inf\n",
    "\n",
    "def haversine(lon1, lat1, lon2, lat2):\n",
    "    \"\"\"\n",
    "    Calculate the great circle distance between two points \n",
    "    on the earth (specified in decimal degrees)\n",
    "    \"\"\"\n",
    "    # convert decimal degrees to radians \n",
    "    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])\n",
    "\n",
    "    # haversine formula \n",
    "    dlon = lon2 - lon1 \n",
    "    dlat = lat2 - lat1 \n",
    "    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2\n",
    "    c = 2 * asin(sqrt(a)) \n",
    "    r = 6371 # Radius of earth in kilometers. Use 3956 for miles\n",
    "    return c * r\n",
    "\n",
    "# this function converts two floats to a point that is recognised by Shapely\n",
    "def point_to_dist(row):\n",
    "    dist = haversine(row[\"geometry\"].y, row[\"geometry\"].x, cbd_loc.y, cbd_loc.x)\n",
    "    return dist\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'vic_centroid_sf' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-4-a73ec7afb3ae>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mX2\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mDataFrame\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX2\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mX2\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m\"count\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[0mX3\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mvic_centroid_sf\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX2\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhow\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'inner'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[0mon\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'SA2_NAME21'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mX3\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'cbd_dist'\u001b[0m\u001b[1;33m]\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mX3\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mapply\u001b[0m \u001b[1;33m(\u001b[0m\u001b[1;32mlambda\u001b[0m \u001b[0mrow\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mpoint_to_dist\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrow\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maxis\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'vic_centroid_sf' is not defined"
     ]
    }
   ],
   "source": [
    "X2 = X[['SA2_NAME21']].groupby(by=\"SA2_NAME21\")[\"SA2_NAME21\"].count()\n",
    "X2 = pd.DataFrame(X2)\n",
    "X2.columns=[\"count\"]\n",
    "X3 = vic_centroid_sf.join(X2, how='inner',on='SA2_NAME21')\n",
    "\n",
    "X3['cbd_dist'] = X3.apply (lambda row: point_to_dist(row), axis=1)\n",
    "X3.sort_values(by=['cbd_dist'], inplace=True)\n",
    "X3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'X3' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-5-ae5fd4cac5c2>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mpruned_X3\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mX3\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'SA2_NAME21'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"cbd_dist\"\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[0mpruned_X3\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mset_index\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'SA2_NAME21'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0minplace\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mpruned_X3\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;31m#pruned_X3.join(X, how='left', on=\"SA2_NAME21\")\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mNameError\u001b[0m: name 'X3' is not defined"
     ]
    }
   ],
   "source": [
    "pruned_X3 = X3[['SA2_NAME21', \"cbd_dist\"]]\n",
    "pruned_X3.set_index('SA2_NAME21', inplace=True)\n",
    "pruned_X3\n",
    "#pruned_X3.join(X, how='left', on=\"SA2_NAME21\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'pruned_X3' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-6-14012f1b58f5>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[0mX_dists\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mX\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mjoin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mpruned_X3\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhow\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'left'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mon\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"SA2_NAME21\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m: name 'pruned_X3' is not defined"
     ]
    }
   ],
   "source": [
    "X_dists = X.join(pruned_X3, how='left', on=\"SA2_NAME21\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\tnum training instances:  10860\n"
     ]
    }
   ],
   "source": [
    "sl = 50\n",
    "scaler = StandardScaler()\n",
    "numeric_features = [ \n",
    "                  \"Median_tot_prsnl_inc_weekly\", \n",
    "                  \"Median_rent_weekly\",\n",
    "                  \"Median_tot_fam_inc_weekly\", \n",
    "                  \"Median_tot_hhd_inc_weekly\", \n",
    "                  \"total_population\",\n",
    "                  \"Bed\", \n",
    "                  \"Bath\", \n",
    "                  \"Park\",\n",
    "                  \"Offence Count\",\n",
    "                  \"cbd_dist\"]\n",
    "numeric_transformer = Pipeline(steps=[\n",
    "    ('scaler', StandardScaler())])\n",
    "\n",
    "preprocessor = ColumnTransformer(\n",
    "    transformers=[\n",
    "        ('num', scaler, numeric_features)])\n",
    "\n",
    "y = X_dists['cost_text'].tolist()\n",
    "print(\"\\tnum training instances: \", len(y))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(10860, 12)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data = X_dists.drop([\"index\", \"address\", \"desc_head\", \"latitude\", \"longitude\", \"LocID\", \"SA2_CODE_2021\", \n",
    "              \"cost_text\", \"SA2_NAME21\"], axis=1)\n",
    "data.astype({ \n",
    "          \"Median_tot_prsnl_inc_weekly\":\"float\", \n",
    "          \"Median_rent_weekly\":\"float\",\n",
    "          \"Median_tot_fam_inc_weekly\":\"float\", \n",
    "          \"Median_tot_hhd_inc_weekly\":\"float\", \n",
    "          \"total_population\": \"int64\",\n",
    "          \"duration_mins\": \"category\", \n",
    "          \"Bed\":\"int32\", \n",
    "          \"Bath\":\"int32\", \n",
    "          \"Park\":\"int32\",\n",
    "          \"property_type\":\"category\",\n",
    "          #\"SA2_NAME21\": \"category\",\n",
    "          \"Offence Count\": \"int32\",\n",
    "          \"cbd_dist\": \"float\"}).dtypes\n",
    "data.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "# define base model\n",
    "def baseline_model():\n",
    "    # create model\n",
    "    model = Sequential()\n",
    "    model.add(Dense(100, input_shape=(12,), kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(32, kernel_initializer='normal', activation='relu'))\n",
    "    model.add(Dense(1, kernel_initializer='normal', activation=\"sigmoid\"))\n",
    "    # Compile model\n",
    "    model.compile(loss='mean_squared_error', optimizer='adam')\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-10-01 13:20:56.052124: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination\n",
      "2022-10-01 13:20:56.052168: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: uwu\n",
      "2022-10-01 13:20:56.052176: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: uwu\n",
      "2022-10-01 13:20:56.052288: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 515.65.1\n",
      "2022-10-01 13:20:56.052312: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 390.154.0\n",
      "2022-10-01 13:20:56.052318: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 390.154.0 does not match DSO version 515.65.1 -- cannot find working devices in this configuration\n",
      "2022-10-01 13:20:56.052616: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[nan nan nan nan nan nan nan nan nan nan]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
      "10 fits failed out of a total of 10.\n",
      "The score on these train-test partitions for these parameters will be set to nan.\n",
      "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
      "\n",
      "Below are more details about the failures:\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_1\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_2\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_3\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_4\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_5\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_6\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_7\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_8\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "--------------------------------------------------------------------------------\n",
      "1 fits failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 762, in fit\n",
      "    self._fit(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 931, in _fit\n",
      "    self._fit_keras_model(\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/scikeras/wrappers.py\", line 526, in _fit_keras_model\n",
      "    hist = self.model_.fit(x=X, y=y, **fit_args)\n",
      "  File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "    raise e.with_traceback(filtered_tb) from None\n",
      "  File \"/tmp/__autograph_generated_file3bw40e6h.py\", line 15, in tf__train_function\n",
      "    retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)\n",
      "ValueError: in user code:\n",
      "\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1160, in train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1146, in step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 1135, in run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/training.py\", line 993, in train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n",
      "        raise e.with_traceback(filtered_tb) from None\n",
      "    File \"/home/sesshah/anaconda3/lib/python3.9/site-packages/keras/engine/input_spec.py\", line 295, in assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer \"sequential_9\" is incompatible with the layer: expected shape=(None, 12), found shape=(None, 10)\n",
      "\n",
      "\n",
      "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n"
     ]
    }
   ],
   "source": [
    "estimator = KerasRegressor(model=baseline_model, epochs=200, verbose=0)\n",
    "kfold = KFold(n_splits=10, shuffle=True, random_state=30027)\n",
    "\n",
    "results = cross_val_score(estimator, preprocessor.fit_transform(data), y, cv=kfold)\n",
    "print(results)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
